/**
 * OPEC OpsFlow - Permissions & UI Access Utility
 * Primary source of truth for what a user can see and do.
 */

import { User, PermissionProfile, ModulePermission, DeptType, AccessLevel } from './types';
import { inferDeptAndLevel, isAdminUser } from './auth-mapping';

/**
 * Standard Module Keys for the entire system
 */
export type ModuleKey = 
  | 'overview_dashboard'
  | 'customers'
  | 'main_contracts'
  | 'customer_pos'
  | 'timesheets'
  | 'worker_payroll'
  | 'office_payroll'
  | 'positions'
  | 'workers'
  | 'office_staff'
  | 'waves'
  | 'assignments'
  | 'mobilization'
  | 'vendors'
  | 'purchases'
  | 'store_inventory'
  | 'billing_notes'
  | 'tax_invoices'
  | 'receipts'
  | 'ap_bills'
  | 'accounts_receivable'
  | 'accounts_payable'
  | 'cashbook'
  | 'bank_accounts'
  | 'system_admin'
  | 'client_portal';

/**
 * Default Permission Templates
 */
const FULL_ACCESS: ModulePermission = { view: true, create: true, edit: true, delete: true, approve: true };
const OFFICER_ACCESS: ModulePermission = { view: true, create: true, edit: true, delete: false, approve: false };
const READ_ONLY: ModulePermission = { view: true, create: false, edit: false, delete: false, approve: false };
const NO_ACCESS: ModulePermission = { view: false, create: false, edit: false, delete: false, approve: false };

/**
 * Baseline Permission Profile Definitions
 */
export function getBaselineProfiles(): Partial<PermissionProfile>[] {
  const baseline = (key: string, nameEn: string, nameTh: string, dept: DeptType, level: AccessLevel, perms: Record<string, ModulePermission>) => ({
    profileKey: key,
    profileNameEn: nameEn,
    profileNameTh: nameTh,
    department: dept,
    level: level,
    isActive: true,
    notes: 'Generated by system baseline tool',
    permissions: {
      ...INITIAL_PERMISSIONS_TEMPLATE,
      ...perms
    }
  });

  return [
    // 1. Admin Admin
    baseline('admin_admin', 'System Administrator', 'ผู้ดูแลระบบสูงสุด', 'admin', 'admin', 
      Object.keys(INITIAL_PERMISSIONS_TEMPLATE).reduce((acc, k) => ({ ...acc, [k]: FULL_ACCESS }), {})
    ),

    // 2. HR Officer
    baseline('hr_officer', 'HR Officer', 'เจ้าหน้าที่ฝ่ายบุคคล', 'hr', 'officer', {
      overview_dashboard: READ_ONLY,
      positions: OFFICER_ACCESS,
      workers: OFFICER_ACCESS,
      timesheets: OFFICER_ACCESS,
      worker_payroll: OFFICER_ACCESS,
      waves: OFFICER_ACCESS,
      assignments: OFFICER_ACCESS,
      mobilization: OFFICER_ACCESS,
      office_staff: READ_ONLY,
      store_inventory: READ_ONLY
    }),

    // 3. HR Manager
    baseline('hr_manager', 'HR Manager', 'ผู้จัดการฝ่ายบุคคล', 'hr', 'manager', {
      overview_dashboard: READ_ONLY,
      positions: { ...OFFICER_ACCESS, approve: true },
      workers: { ...OFFICER_ACCESS, approve: true },
      timesheets: { ...OFFICER_ACCESS, approve: true },
      worker_payroll: { ...OFFICER_ACCESS, approve: true },
      office_payroll: { ...OFFICER_ACCESS, approve: true },
      office_staff: { ...OFFICER_ACCESS, approve: true },
      waves: OFFICER_ACCESS,
      assignments: OFFICER_ACCESS,
      mobilization: OFFICER_ACCESS,
      store_inventory: READ_ONLY
    }),

    // 4. Sales Officer
    baseline('sales_officer', 'Sales Officer', 'เจ้าหน้าที่ฝ่ายขาย', 'sales', 'officer', {
      overview_dashboard: READ_ONLY,
      customers: OFFICER_ACCESS,
      main_contracts: OFFICER_ACCESS,
      customer_pos: OFFICER_ACCESS,
      waves: READ_ONLY,
      assignments: READ_ONLY,
      mobilization: READ_ONLY,
      billing_notes: READ_ONLY
    }),

    // 5. Operations Officer
    baseline('operations_officer', 'Operations Officer', 'เจ้าหน้าที่ฝ่ายปฏิบัติการ', 'operations', 'officer', {
      overview_dashboard: READ_ONLY,
      waves: OFFICER_ACCESS,
      assignments: OFFICER_ACCESS,
      mobilization: OFFICER_ACCESS,
      purchases: OFFICER_ACCESS,
      timesheets: OFFICER_ACCESS,
      customers: READ_ONLY,
      main_contracts: READ_ONLY,
      customer_pos: READ_ONLY,
      positions: READ_ONLY,
      workers: READ_ONLY,
      vendors: READ_ONLY,
      store_inventory: READ_ONLY
    }),

    // 6. Store Officer
    baseline('store_officer', 'Store Officer', 'เจ้าหน้าที่คลังสินค้า', 'store', 'officer', {
      overview_dashboard: READ_ONLY,
      vendors: OFFICER_ACCESS,
      purchases: OFFICER_ACCESS,
      store_inventory: OFFICER_ACCESS,
      positions: READ_ONLY,
      workers: READ_ONLY,
      waves: READ_ONLY,
      assignments: READ_ONLY,
      mobilization: READ_ONLY,
      ap_bills: READ_ONLY
    }),

    // 7. Accounting Officer
    baseline('accounting_officer', 'Accounting & Finance Officer', 'เจ้าหน้าที่บัญชีและการเงิน', 'accounting', 'officer', {
      overview_dashboard: READ_ONLY,
      billing_notes: OFFICER_ACCESS,
      tax_invoices: OFFICER_ACCESS,
      receipts: OFFICER_ACCESS,
      ap_bills: OFFICER_ACCESS,
      accounts_receivable: READ_ONLY,
      accounts_payable: READ_ONLY,
      cashbook: OFFICER_ACCESS,
      bank_accounts: OFFICER_ACCESS,
      customers: READ_ONLY,
      main_contracts: READ_ONLY,
      customer_pos: READ_ONLY,
      vendors: READ_ONLY,
      purchases: READ_ONLY,
      store_inventory: READ_ONLY,
      worker_payroll: READ_ONLY,
      office_payroll: READ_ONLY,
      office_staff: READ_ONLY,
      waves: READ_ONLY,
      assignments: READ_ONLY
    }),

    // 8. Client Viewer
    baseline('client_viewer', 'Client Viewer', 'ลูกค้า (Viewer)', 'client', 'viewer', {
      client_portal: READ_ONLY
    })
  ];
}

const INITIAL_PERMISSIONS_TEMPLATE: Record<string, ModulePermission> = {
  overview_dashboard: NO_ACCESS,
  customers: NO_ACCESS,
  main_contracts: NO_ACCESS,
  customer_pos: NO_ACCESS,
  timesheets: NO_ACCESS,
  worker_payroll: NO_ACCESS,
  office_payroll: NO_ACCESS,
  positions: NO_ACCESS,
  workers: NO_ACCESS,
  office_staff: NO_ACCESS,
  waves: NO_ACCESS,
  assignments: NO_ACCESS,
  mobilization: NO_ACCESS,
  vendors: NO_ACCESS,
  purchases: NO_ACCESS,
  store_inventory: NO_ACCESS,
  billing_notes: NO_ACCESS,
  tax_invoices: NO_ACCESS,
  receipts: NO_ACCESS,
  ap_bills: NO_ACCESS,
  accounts_receivable: NO_ACCESS,
  accounts_payable: NO_ACCESS,
  cashbook: NO_ACCESS,
  bank_accounts: NO_ACCESS,
  system_admin: NO_ACCESS,
  client_portal: NO_ACCESS,
};

/**
 * Primary helper to check permissions for a specific module
 */
export function getPermissions(
  user: User | null, 
  moduleKey: ModuleKey, 
  profile?: PermissionProfile | null
): ModulePermission {
  if (!user || !user.isActive || user.approvalStatus !== 'ACTIVE') return NO_ACCESS;

  // 1. Full Admin Override
  if (isAdminUser(user)) {
    return FULL_ACCESS;
  }

  // 2. Profile-based check (Primary)
  if (profile && profile.isActive && profile.permissions?.[moduleKey]) {
    return profile.permissions[moduleKey];
  }

  // 3. Temporary Legacy Fallback logic while migrating
  const { dept, level } = inferDeptAndLevel(user);
  const isOfficer = level === 'officer' || level === 'manager' || level === 'admin';
  
  if (moduleKey === 'overview_dashboard') return READ_ONLY;
  
  return NO_ACCESS;
}

/**
 * Functional shorthand helpers
 */
export const canView = (user: User | null, moduleKey: ModuleKey, profile?: PermissionProfile | null) => 
  getPermissions(user, moduleKey, profile).view;

export const canCreate = (user: User | null, moduleKey: ModuleKey, profile?: PermissionProfile | null) => 
  getPermissions(user, moduleKey, profile).create;

export const canEdit = (user: User | null, moduleKey: ModuleKey, profile?: PermissionProfile | null) => 
  getPermissions(user, moduleKey, profile).edit;

export const canDelete = (user: User | null, moduleKey: ModuleKey, profile?: PermissionProfile | null) => 
  getPermissions(user, moduleKey, profile).delete;

export const canApprove = (user: User | null, moduleKey: ModuleKey, profile?: PermissionProfile | null) => 
  getPermissions(user, moduleKey, profile).approve;
