
'use client';

/**
 * @fileOverview OPEC OpsFlow - Permissions & UI Access Utility
 * Primary source of truth for what a user can see and do.
 * Maps operational intents (e.g., "Generate Payroll") to the ModulePermission matrix.
 */

import { User, PermissionProfile, ModulePermission, DeptType, AccessLevel } from './types';
import { inferDeptAndLevel, isAdminUser } from './auth-mapping';

/**
 * Standard Module Keys for the entire system
 */
export type ModuleKey = 
  | 'overview_dashboard'
  | 'customers'
  | 'main_contracts'
  | 'customer_pos'
  | 'quotations'
  | 'timesheets'
  | 'worker_payroll'
  | 'office_payroll'
  | 'positions'
  | 'workers'
  | 'office_staff'
  | 'waves'
  | 'assignments'
  | 'mobilization'
  | 'vendors'
  | 'purchases'
  | 'store_inventory'
  | 'billing_notes'
  | 'tax_invoices'
  | 'receipts'
  | 'ap_bills'
  | 'accounts_receivable'
  | 'accounts_payable'
  | 'cashbook'
  | 'bank_accounts'
  | 'system_admin'
  | 'client_portal'
  | 'document_numbering'
  | 'sales_contract_terms'
  | 'labor_cost_contract_terms'
  | 'rate_conditions'
  | 'profit_estimates'
  | 'payment_export_batches'
  | 'audit_logs';

/**
 * Default Permission Templates
 */
export const FULL_ACCESS: ModulePermission = { view: true, create: true, edit: true, delete: true, approve: true };
export const OFFICER_ACCESS: ModulePermission = { view: true, create: true, edit: true, delete: false, approve: false };
export const READ_ONLY: ModulePermission = { view: true, create: false, edit: false, delete: false, approve: false };
export const NO_ACCESS: ModulePermission = { view: false, create: false, edit: false, delete: false, approve: false };

export const INITIAL_PERMISSIONS_TEMPLATE: Record<string, ModulePermission> = {
  overview_dashboard: NO_ACCESS,
  customers: NO_ACCESS,
  main_contracts: NO_ACCESS,
  customer_pos: NO_ACCESS,
  quotations: NO_ACCESS,
  timesheets: NO_ACCESS,
  worker_payroll: NO_ACCESS,
  office_payroll: NO_ACCESS,
  positions: NO_ACCESS,
  workers: NO_ACCESS,
  office_staff: NO_ACCESS,
  waves: NO_ACCESS,
  assignments: NO_ACCESS,
  mobilization: NO_ACCESS,
  vendors: NO_ACCESS,
  purchases: NO_ACCESS,
  store_inventory: NO_ACCESS,
  billing_notes: NO_ACCESS,
  tax_invoices: NO_ACCESS,
  receipts: NO_ACCESS,
  ap_bills: NO_ACCESS,
  accounts_receivable: NO_ACCESS,
  accounts_payable: NO_ACCESS,
  cashbook: NO_ACCESS,
  bank_accounts: NO_ACCESS,
  system_admin: NO_ACCESS,
  client_portal: NO_ACCESS,
  document_numbering: NO_ACCESS,
  sales_contract_terms: NO_ACCESS,
  labor_cost_contract_terms: NO_ACCESS,
  rate_conditions: NO_ACCESS,
  profit_estimates: NO_ACCESS,
  payment_export_batches: NO_ACCESS,
  audit_logs: NO_ACCESS,
};

/**
 * Baseline Permission Profile Definitions
 * Defines standard role-to-module mappings for the Opec OpsFlow platform.
 */
export function getBaselineProfiles(): Partial<PermissionProfile>[] {
  const baseline = (key: string, nameEn: string, nameTh: string, dept: DeptType, level: AccessLevel, perms: Record<string, Partial<ModulePermission>>) => ({
    profileKey: key,
    profileNameEn: nameEn,
    profileNameTh: nameTh,
    department: dept,
    level: level,
    isActive: true,
    notes: 'Generated by system baseline tool',
    permissions: Object.keys(INITIAL_PERMISSIONS_TEMPLATE).reduce((acc, k) => {
      const p = perms[k] || NO_ACCESS;
      return { 
        ...acc, 
        [k]: { ...NO_ACCESS, ...p } 
      };
    }, {} as Record<string, ModulePermission>)
  });

  return [
    // 1. Admin Admin
    baseline('admin_admin', 'System Administrator', 'ผู้ดูแลระบบสูงสุด', 'admin', 'admin', 
      Object.keys(INITIAL_PERMISSIONS_TEMPLATE).reduce((acc, k) => ({ ...acc, [k]: FULL_ACCESS }), {})
    ),

    // 2. HR Manager
    baseline('hr_manager', 'HR Manager', 'ผู้จัดการฝ่ายบุคคล', 'hr', 'manager', {
      overview_dashboard: READ_ONLY,
      positions: { ...OFFICER_ACCESS, approve: true, delete: true },
      workers: { ...OFFICER_ACCESS, approve: true, delete: true },
      timesheets: { view: true, approve: true }, // can view and review_ops
      worker_payroll: { view: true, create: true, approve: true }, // generate, hr_approve
      office_payroll: { view: true, create: true, approve: true },
      office_staff: { ...OFFICER_ACCESS, approve: true },
      waves: READ_ONLY,
      assignments: READ_ONLY,
      mobilization: READ_ONLY,
      labor_cost_contract_terms: { ...OFFICER_ACCESS, approve: true, delete: true },
      rate_conditions: { ...OFFICER_ACCESS, approve: true, delete: true },
      profit_estimates: READ_ONLY,
    }),

    // 3. HR Officer
    baseline('hr_officer', 'HR Officer', 'เจ้าหน้าที่ฝ่ายบุคคล', 'hr', 'officer', {
      overview_dashboard: READ_ONLY,
      positions: OFFICER_ACCESS,
      workers: OFFICER_ACCESS,
      timesheets: { view: true, create: true, edit: true }, // can prep daily logs
      worker_payroll: { view: true }, // support only
      waves: READ_ONLY,
      assignments: READ_ONLY,
      mobilization: READ_ONLY,
      labor_cost_contract_terms: OFFICER_ACCESS,
      rate_conditions: OFFICER_ACCESS,
    }),

    // 4. Operations Manager
    baseline('operations_manager', 'Operations Manager', 'ผู้จัดการฝ่ายปฏิบัติการ', 'operations', 'manager', {
      overview_dashboard: READ_ONLY,
      waves: { ...OFFICER_ACCESS, approve: true, delete: true },
      assignments: { ...OFFICER_ACCESS, approve: true },
      mobilization: { ...OFFICER_ACCESS, approve: true },
      timesheets: { view: true, create: true, edit: true, approve: true }, // create, edit, review_ops
      workers: READ_ONLY,
      positions: READ_ONLY,
      profit_estimates: READ_ONLY,
    }),

    // 5. Operations Officer
    baseline('operations_officer', 'Operations Officer', 'เจ้าหน้าที่ฝ่ายปฏิบัติการ', 'operations', 'officer', {
      overview_dashboard: READ_ONLY,
      waves: OFFICER_ACCESS,
      assignments: OFFICER_ACCESS,
      mobilization: OFFICER_ACCESS,
      timesheets: { view: true, create: true, edit: true }, // create, edit
      workers: READ_ONLY,
    }),

    // 6. Accounting Manager
    baseline('accounting_manager', 'Accounting & Finance Manager', 'ผู้จัดการฝ่ายบัญชีและการเงิน', 'accounting', 'manager', {
      overview_dashboard: READ_ONLY,
      billing_notes: { ...OFFICER_ACCESS, approve: true, delete: true },
      tax_invoices: { ...OFFICER_ACCESS, approve: true, delete: true },
      receipts: { ...OFFICER_ACCESS, approve: true },
      ap_bills: { ...OFFICER_ACCESS, approve: true },
      cashbook: { ...OFFICER_ACCESS, approve: true },
      bank_accounts: { ...OFFICER_ACCESS, approve: true },
      accounts_receivable: READ_ONLY,
      accounts_payable: READ_ONLY,
      worker_payroll: { view: true, edit: true, approve: true }, // finance_prepare, mark_paid, lock
      office_payroll: { view: true, edit: true, approve: true },
      payment_export_batches: { view: true, create: true, approve: true }, // export_bank_file
      sales_contract_terms: READ_ONLY,
      labor_cost_contract_terms: READ_ONLY,
      rate_conditions: READ_ONLY,
      profit_estimates: READ_ONLY,
    }),

    // 7. Accounting Officer
    baseline('accounting_officer', 'Accounting Officer', 'เจ้าหน้าที่ฝ่ายบัญชี', 'accounting', 'officer', {
      overview_dashboard: OFFICER_ACCESS,
      billing_notes: OFFICER_ACCESS,
      tax_invoices: OFFICER_ACCESS,
      receipts: OFFICER_ACCESS,
      ap_bills: OFFICER_ACCESS,
      cashbook: OFFICER_ACCESS,
      accounts_receivable: READ_ONLY,
      accounts_payable: READ_ONLY,
      worker_payroll: { view: true },
      sales_contract_terms: READ_ONLY,
      labor_cost_contract_terms: READ_ONLY,
    }),

    // 8. Sales Manager
    baseline('sales_manager', 'Sales Manager', 'ผู้จัดการฝ่ายขาย', 'sales', 'manager', {
      overview_dashboard: READ_ONLY,
      customers: { ...OFFICER_ACCESS, approve: true, delete: true },
      main_contracts: { ...OFFICER_ACCESS, approve: true, delete: true },
      customer_pos: { ...OFFICER_ACCESS, approve: true },
      quotations: { ...OFFICER_ACCESS, approve: true, delete: true },
      sales_contract_terms: { ...OFFICER_ACCESS, approve: true, delete: true },
      rate_conditions: OFFICER_ACCESS,
      profit_estimates: READ_ONLY,
      billing_notes: READ_ONLY,
    }),

    // 9. Sales Officer
    baseline('sales_officer', 'Sales Officer', 'เจ้าหน้าที่ฝ่ายขาย', 'sales', 'officer', {
      overview_dashboard: READ_ONLY,
      customers: OFFICER_ACCESS,
      main_contracts: OFFICER_ACCESS,
      customer_pos: OFFICER_ACCESS,
      quotations: OFFICER_ACCESS,
      sales_contract_terms: OFFICER_ACCESS,
      profit_estimates: READ_ONLY,
    }),

    // 10. Store Officer
    baseline('store_officer', 'Store & Procurement Officer', 'เจ้าหน้าที่คลังและจัดซื้อ', 'store', 'officer', {
      overview_dashboard: READ_ONLY,
      vendors: OFFICER_ACCESS,
      purchases: OFFICER_ACCESS,
      store_inventory: OFFICER_ACCESS,
      ap_bills: READ_ONLY,
    }),

    // 11. Client Approver
    baseline('client_approver', 'Client Approver', 'ลูกค้า (ผู้อนุมัติ)', 'client', 'manager', {
      client_portal: { view: true, approve: true }, // wave_accept, timesheet_approve
    }),

    // 12. Client Viewer
    baseline('client_viewer', 'Client Viewer', 'ลูกค้า (ผู้เรียกดู)', 'client', 'viewer', {
      client_portal: { view: true, approve: false }, // read-only
    })
  ];
}

/**
 * Primary helper to check permissions for a specific module
 * Maps business "Intents" to the 5 standard boolean flags.
 */
export function getPermissions(
  user: User | null, 
  moduleKey: ModuleKey, 
  profile?: PermissionProfile | null
): ModulePermission {
  if (!user || !user.isActive) return NO_ACCESS;

  // 1. Full Admin Override - High Priority Bypass
  if (isAdminUser(user)) {
    return FULL_ACCESS;
  }

  // 2. Others must be approved to access anything
  if (user.approvalStatus !== 'ACTIVE') {
    return NO_ACCESS;
  }

  // 3. Profile-based check (Primary)
  if (profile && profile.isActive && profile.permissions?.[moduleKey]) {
    return profile.permissions[moduleKey];
  }

  // 4. Graceful Fallback Logic (Legacy Support)
  const { dept, level } = inferDeptAndLevel(user);
  
  if (moduleKey === 'overview_dashboard') return READ_ONLY;
  
  // Basic Operational Fallbacks (Safe defaults)
  if (dept === 'hr' && ['workers', 'positions', 'timesheets', 'worker_payroll'].includes(moduleKey)) return OFFICER_ACCESS;
  if (dept === 'store' && ['store_inventory', 'vendors', 'purchases'].includes(moduleKey)) return OFFICER_ACCESS;
  if (dept === 'accounting' && ['cashbook', 'billing_notes', 'tax_invoices', 'receipts', 'ap_bills'].includes(moduleKey)) return OFFICER_ACCESS;
  if (dept === 'operations' && ['waves', 'assignments', 'mobilization', 'timesheets'].includes(moduleKey)) return OFFICER_ACCESS;
  
  // Automated access scoping for Customer Portal
  if (dept === 'client' && moduleKey === 'client_portal') {
    // If manager (approver), grant approval rights
    return level === 'manager' ? { ...READ_ONLY, approve: true } : READ_ONLY;
  }

  return NO_ACCESS;
}

/**
 * Functional shorthand helpers
 */
export const canView = (user: User | null, moduleKey: ModuleKey, profile?: PermissionProfile | null) => 
  getPermissions(user, moduleKey, profile).view;

export const canCreate = (user: User | null, moduleKey: ModuleKey, profile?: PermissionProfile | null) => 
  getPermissions(user, moduleKey, profile).create;

export const canEdit = (user: User | null, moduleKey: ModuleKey, profile?: PermissionProfile | null) => 
  getPermissions(user, moduleKey, profile).edit;

export const canDelete = (user: User | null, moduleKey: ModuleKey, profile?: PermissionProfile | null) => 
  getPermissions(user, moduleKey, profile).delete;

export const canApprove = (user: User | null, moduleKey: ModuleKey, profile?: PermissionProfile | null) => 
  getPermissions(user, moduleKey, profile).approve;
